version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo # т.е запускаем контейнер после запуска mongo
    networks:
      - appnet # общая сеть для связи контейнеров 

  mongo:
    image: mongo
    networks:
      - appnet

networks:
  appnet:
    driver: bridge # мостовой драйвер

