version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - DB=testdb
    command: ["sh", "-c", "sleep 10 && python3 create_db.py && python3 app.py"]
